server:
  port: 19000
  context-path: /sso

eureka:
  client:
      service-url:
        defaultZone: http://192.168.0.88:18001/eureka
  instance:
    #此配置建议只试用开发和测试环境
    #心跳间隔时间,默认是30秒
    leaseRenewalIntervalInSeconds: 1
    #最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true

spring:
  application:
    name: sso-server
  datasource:
    url: jdbc:mysql://192.168.0.88:3306/SSO_SERVER_DB?characterEncoding=utf8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
# Specify the DBMS
  jpa:
   database: MYSQL
# Show or not log for each sql query
   show-sql: true
# Hibernate ddl auto (create, create-drop, update)
   hibernate:
      ddl-auto: update
      name-strategy: org.hibernate.cfg.improvedNamingStrategy
# Naming strategy
# stripped before adding them to the entity manager)
   properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
          use_query_cache: false

security:
  oauth2:
    client:
      client-id: wmp
      client-secret: wmpsecret
      scope: read,write
      auto-approve-scopes: '.*'
    authorization:
      check-token-access: permitAll()

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG